# Generated by Django 2.1 on 2020-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200424_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=300),
        ),
    ]
